apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: oadp-bucket
  namespace: openshift-adp
spec:
  generateBucketName: oadp-backup
  storageClassName: openshift-storage.noobaa.io

