---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: openshift-adp
stringData:
  cloud: |
    [default]
    aws_access_key_id = 1230W995OIERV0U0HXMQE
    aws_secret_access_key = 8kHEKyCD1fCmD4QmnN05NZuNctCni0fVXYimTIj
type: Opaque
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: oadp-bucket
  namespace: openshift-adp
spec:
  generateBucketName: oadp-backup
  storageClassName: openshift-storage.noobaa.io
---
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: oadp-dpa
  namespace: openshift-adp
spec:
  backupLocations:
    - velero:
        provider: aws
        config:
          region: "noobaa"
        credential:
          name: cloud-credentials
          key: cloud
        default: true
        objectStorage:
          bucket: oadp-bucket
          prefix: velero
  configuration:
    velero:
      defaultPlugins:
        - openshift
        - aws
    nodeAgent:
      uploaderType: kopia
  snapshotLocations: []
