apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  labels:
    app: keycloak
type: Opaque
stringData:
  # Change these values for production
  POSTGRES_DATABASE: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: "Asdf@1234" 
  # This is the username and password Keycloak will use
  username: keycloak
  password: "Asdf@1234"



