apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-service
  namespace: keycloak
  labels:
    app: postgresql-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql-db